### ISSUE TITLE
DOM Being Queried Even if Function is not Invoked!

### ISSUE THREAD

**Issue by manavm1990** [swic-cis-277/in-class-rwd#4]
https://github.com/swic-cis-277/in-class-rwd/blob/206351f1838818154c597bbfd6de0df51f7c501e/client/lib/form/toggles.js#L4

`fields` should be 'enclosed' inside `toggles` exported _function;_ it should only be _referenced_ upon [_invocation_ within the `switch`](https://github.com/swic-cis-277/in-class-rwd/blob/206351f1838818154c597bbfd6de0df51f7c501e/client/scripts.js#L8).

However, even on home page, there is a 'console error' about `null` as the DOM is being queried for `form`. What am I misunderstanding here?

**Comment by minifyre** [comment]
Line 4 will be invoked as soon as it is read. To fix it, you can move it into function to get it to be invoked when you want it to.
